using System;

namespace FS.TimeTracking.ReportServer.Abstractions.DTOs.Reporting;

/// <summary>
/// Report input parameters.
/// </summary>
/// <autogeneratedoc />
public class ReportParameterDto
{
    /// <summary>
    /// The type of the activity report.
    /// </summary>
    public ActivityReportType ReportType { get; set; }

    /// <summary>
    /// Gets or sets the report culture.
    /// </summary>
    public string Culture { get; set; }

    /// <summary>
    /// Gets or sets the time zone used to convert date/time values to.
    /// </summary>
    public string TargetTimeZoneId { get; set; }

    /// <summary>
    /// Gets or sets the start date.
    /// </summary>
    public DateTimeOffset StartDate { get; set; }

    /// <summary>
    /// Gets or sets the end date.
    /// </summary>
    public DateTimeOffset EndDate { get; set; }
}